# Site settings
title:
email:
description: > KpBioTeam hope you find this site a useful source of information about BioIT research at University of Bradford.   
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:kpbioteam
email:kpbioteam@gmail.com
facebook_username:
twitter_username:bioinfbrad
github_username:kpbioteam
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
